export const LOGIN = "LOGIN";
export const PROJECT = "PROJECT";
export const CONNECT = "CONNECT";
export const TABTYPE = "TABTYPE";
export const ANALYZEDETAIL = "ANALYZEDETAIL";
export const PROJECTTRANSFORMDETAILS = "PROJECTTRANSFORMDETAILS";
export const DESIGNDETAILS = "DESIGNDETAILS"

