name: React CI

on:
  push:
    branches:
      - "master"
      - "dev_uat"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{contains(github.event.head_commit.message, ' --deploy') }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [14.17.x]

    # if: ${{ github.ref == 'refs/heads/dev_uat' }}
    if: contains('refs/heads/dev_uat', github.ref)
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1

        with:
          role-to-assume: arn:aws:iam::555646157689:role/github-actions-website-upload-role

          aws-region: us-west-1
      - name: Generating Next JS Build
        run: npm install && npm run build
      - name: Deploying  build to S3 bucket
        run: aws s3 sync ./out/ s3://dev.nuodata.io --delete

      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}

    # if: ${{ github.ref == 'refs/heads/master' }}
    if: contains('refs/heads/master', github.ref)
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1

        with:
          role-to-assume: arn:aws:iam::471681951701:role/github-actions-website-upload-role

          aws-region: us-west-1
      - name: Generating Next JS Build
        run: npm install && npm run build
      - name: Deploying  build to S3 bucket
        run: aws s3 sync ./out/ s3://nuodata.io --delete

      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}